print('W czym wampiry jedzą zupy?')
input()
print('W naczyniach krwionośnych!')
print()
print('Co dentyści nazywają \'czarnymi dziurami\'?')
input()
print('Ubytki w uzębieniu kosmonautów!')
print()
print('Puk puk.')
input()
print("Kto tam?")
input()
print('Przerywająca krowa.')
input()
print('Ktooo? Przerywa...', end='')
print('-MUUUUUU!')
